plugins {
    id 'com.lagradost.cloudstream'
}

cloudstream {
    // The version ID of the plugin. Increment this when releasing an update.
    requiresResources = false

    language = "en"
    // The id of the plugin. This is used to uniquely identify the plugin.
    // It must not contain any uppercase letters.
    pluginName = "indflix"
    // The display name of the plugin. This is shown to the user.
    pluginClassName = "IndflixProvider"
}
